"use client";
import React, { useState } from 'react';
import Navbar from '../../components/Navbar';
import { BookOpen, Download, Loader2 } from 'lucide-react';

export default function BookGenerator() {
  const [topic, setTopic] = useState('');
  const [loading, setLoading] = useState(false);
  const [generated, setGenerated] = useState(false);

  const handleGenerate = () => {
    if (!topic) return;
    setLoading(true);
    setTimeout(() => {
      setLoading(false);
      setGenerated(true);
    }, 2500);
  };

  return (
    <div className="min-h-screen bg-background text-white">
      <Navbar />
      <div className="max-w-4xl mx-auto pt-32 px-6 text-center">
        <BookOpen className="w-16 h-16 text-primary mx-auto mb-6" />
        <h1 className="text-4xl font-display font-bold mb-4">Book Generator</h1>
        <p className="text-gray-400 mb-12">Generate complete online books and PDFs from simple prompts.</p>
        
        {!generated ? (
          <div className="glass-panel p-8 rounded-2xl border border-white/5 max-w-2xl mx-auto">
            <textarea 
              value={topic}
              onChange={(e) => setTopic(e.target.value)}
              placeholder="What should the book be about? e.g. A comprehensive guide to starting an AI agency..." 
              className="w-full bg-surface border border-white/10 rounded-xl px-4 py-3 outline-none focus:border-primary h-32 resize-none mb-6 text-white"
            />
            <button 
              onClick={handleGenerate}
              className="w-full bg-primary text-white py-4 rounded-xl font-bold flex items-center justify-center gap-2 hover:bg-primary/80 transition-colors"
            >
              {loading ? <Loader2 className="animate-spin" /> : "Generate Book"}
            </button>
          </div>
        ) : (
          <div className="glass-panel p-12 rounded-2xl border border-primary max-w-2xl mx-auto shadow-neon animate-in zoom-in-95">
            <h2 className="text-3xl font-bold mb-4">{topic}</h2>
            <p className="text-gray-400 mb-8">Your book has been successfully generated by our AI engines!</p>
            <div className="flex gap-4 justify-center">
              <button className="bg-surface border border-white/10 px-6 py-3 rounded-xl hover:bg-white/5 flex items-center gap-2">
                Read Online
              </button>
              <button className="bg-primary text-white px-6 py-3 rounded-xl hover:bg-primary/80 flex items-center gap-2 shadow-neon">
                <Download size={20} /> Download PDF
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
